package com.infogain.demo.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.infogain.demo.constants.ProjectType;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(value = "Project Details", description = "Request body for Project Related Operations")
public class Project {

	@ApiModelProperty(value = "Name Of The Project", required = true, example = "FedEx", allowEmptyValue = false, dataType = "String", name = "projectName", position = 2)
	@JsonProperty(value = "projectName")
	String name;
	@ApiModelProperty(value = "Type of Project", required = true, example = "DEVELOPMENTAL")
	ProjectType projectType;
	@ApiModelProperty(value = "Autogenerated project Id", required = true, hidden = true, notes = "This will be generated automatically at service layer")
	@JsonIgnore
	int projectId;

	/**
	 * @param name
	 * @param projectType
	 * @param projectId
	 */
	public Project(String name, ProjectType projectType, int projectId) {
		this.name = name;
		this.projectType = projectType;
		this.projectId = projectId;
	}

	/**
	 * 
	 */
	public Project() {
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * @return the projectType
	 */
	public ProjectType getProjectType() {
		return projectType;
	}

	/**
	 * @param projectType the projectType to set
	 */
	public void setProjectType(ProjectType projectType) {
		this.projectType = projectType;
	}

	/**
	 * @return the projectId
	 */
	public int getProjectId() {
		return projectId;
	}

	/**
	 * @param projectId the projectId to set
	 */
	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Project [name=").append(name).append(", projectType=").append(projectType)
				.append(", projectId=").append(projectId).append("]");
		return builder.toString();
	}

}
