package com.infogain.demo.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.infogain.demo.constants.UserTypes;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(value = "User", description = "Request body for User Related Operations")
public class User {

	@ApiModelProperty(value = "Name Of The User", required = true, example = "Rudhra Koul", allowEmptyValue = false, dataType = "String", name = "fullName", position = 2)
	@JsonProperty(value = "fullName")
	String name;
	@ApiModelProperty(value = "Age Of The User", required = true, example = "30", allowEmptyValue = false, position = 1)
	int age;
	@ApiModelProperty(value = "Type of user", required = true, example = "DELEVLOPER")
	UserTypes userType;
	@ApiModelProperty(value = "Autogenerated user Id", required = true, hidden = true, notes = "This will be generated automatically at service layer")
	@JsonIgnore
	int userId;

	/**
	 * @param name
	 * @param age
	 * @param userType
	 * @param userId
	 */
	public User(String name, int age, UserTypes userType, int userId) {
		this.name = name;
		this.age = age;
		this.userType = userType;
		this.userId = userId;
	}

	/**
	 * 
	 */
	public User() {
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * @return the age
	 */
	public int getAge() {
		return age;
	}

	/**
	 * @param age the age to set
	 */
	public void setAge(int age) {
		this.age = age;
	}

	/**
	 * @return the userType
	 */
	public UserTypes getUserType() {
		return userType;
	}

	/**
	 * @param userType the userType to set
	 */
	public void setUserType(UserTypes userType) {
		this.userType = userType;
	}

	/**
	 * @return the userId
	 */
	public int getUserId() {
		return userId;
	}

	/**
	 * @param userId the userId to set
	 */
	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("User [name=").append(name).append(", age=").append(age).append(", userType=").append(userType)
				.append(", userId=").append(userId).append("]");
		return builder.toString();
	}

}
